### ISSUE TITLE
Error occurred while enabling FancyPortals in 1.12-pre5

### ISSUE THREAD

**Issue by PsychoLynx** [TWSSYesterday/FancyPortals#1]
Using the latest 1.12-pre5 Spigot

[16:01:50] [Server thread/INFO]: [FancyPortals] Enabling FancyPortals v0.1.0
[16:01:50] [Server thread/ERROR]: Error occurred while enabling FancyPortals v0.1.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at me.bimmr.fancyportals.Util.FileManager.reloadPortals(FileManager.java:46) ~[?:?]
	at me.bimmr.fancyportals.Util.FileManager.getPortals(FileManager.java:28) ~[?:?]
	at me.bimmr.fancyportals.Portals.PortalHandler.<init>(PortalHandler.java:23) ~[?:?]
	at me.bimmr.fancyportals.FancyPortals.onEnable(FancyPortals.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by FlippantCactus** [comment]
Not thought about updating it.
